name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install basedpyright==1.12.1 ruff==0.3.5

      - name: Ruff (lint)
        run: ruff check

      - name: Based Pyright (type check)
        run: basedpyright
